### ISSUE TITLE
More Code!!!

### ISSUE THREAD

**Issue by devonwesley** [noahextime/sprint1#4]
Hey Noah this repo is pretty dry. Put some more files in the repo, CSS, HTML, JS, etc.

**Comment by noahextime** [comment]
I think I fixed the issue, checkout the latest version.

**Comment by devonwesley** [comment]
Wheres the pull request for those changes.? you updated that master without making a pull request.  ? @noahextime

**Comment by noahextime** [comment]
I was missing a step!  I realized I needed to commit my changes to the branch to be merged and then generate a pull request.  Right?

**Comment by devonwesley** [comment]
Yes! that would be a typical git flow if you were on a team. Just think of me as your team member for this project.
